services:
  tinymon:
    image: tinymon
    build:
      context: .
      dockerfile: Tinymon/Dockerfile
    ports:
      - 5119:8080
    profiles:
      - app

  tinymondb:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres